# Form implementation generated from reading ui file 'untitled4.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow4(object):
    def setupUi(self, MainWindow4):
        MainWindow4.setObjectName("MainWindow4")
        MainWindow4.resize(815, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow4)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(parent=self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(190, 10, 601, 531))
        self.dial.setObjectName("dial")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 142, 141, 91))
        self.pushButton.setObjectName("pushButton")
        MainWindow4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 33))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow4)
        self.statusbar.setObjectName("statusbar")
        MainWindow4.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(parent=MainWindow4)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(parent=MainWindow4)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow4)

    def retranslateUi(self, MainWindow4):
        _translate = QtCore.QCoreApplication.translate
        MainWindow4.setWindowTitle(_translate("MainWindow4", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow4", "播放"))
        self.menu.setTitle(_translate("MainWindow4", "到其它界面"))
        self.action.setText(_translate("MainWindow4", "第一个界面"))
        self.action_2.setText(_translate("MainWindow4", "第二个界面"))
